# Generated by Django 5.0.2 on 2024-10-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_main', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=20),
        ),
    ]
