# Generated by Django 5.0.2 on 2024-10-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_main', '0003_alter_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
